services:
  mongodb-service:
    image: mongo:latest
    container_name: projectName-mongodb
    restart: always
    ports:
      - '27018:${MONGODB_PORT}'
    env_file:
      - ./../../.env
    environment:
      MONGO_USERNAME: ${MONGODB_USERNAME}
      MONGO_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_DB_NAME: ${MONGODB_DB_NAME}
    volumes:
      - mongodb_data:/data/db
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
    networks:
      - app-network

  nextjs-service:
    build:
      context: ./../../
      dockerfile: ./docker/production/Dockerfile.nextjs
    container_name: projectName-nextjs
    image: nextjs-service
    restart: always
    ports:
      - '3003:3000'
    env_file:
      - ./../../.env
    environment:
      VIPS_CONCURRENCY: 16 # Value of thread mathcing number of CPU cores
    depends_on:
      - mongodb-service
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
